// 慢性病配置（前端展示/交互用）
// 说明：
// - showFlag：是否启用/需要在表单中展示填写
// - defaultHasFlag：默认“有/无”（当历史数据里没有该 key 时生效）
// - hasFlag：仅表示用户当前选择；不建议写在此配置里（保存到数据库时会生成）
export const chronicDiseaseConfig = [
  { id: 1, key: "hypertension", name: "高血压", showFlag: true, defaultHasFlag: false },
  { id: 2, key: "coronaryHeartDisease", name: "冠心病", showFlag: true, defaultHasFlag: false },
  { id: 3, key: "heartFailure", name: "心功能不全", showFlag: true, defaultHasFlag: false },
  { id: 4, key: "chronicObstructivePulmonaryDisease", name: "慢性阻塞性肺疾病", showFlag: true, defaultHasFlag: false },
  { id: 5, key: "bronchialAsthma", name: "支气管哮喘", showFlag: true, defaultHasFlag: false },
  { id: 6, key: "ulcerativeColitis", name: "溃疡性结肠炎", showFlag: true, defaultHasFlag: false },
  { id: 7, key: "advancedSchistosomiasis", name: "晚期血吸虫病", showFlag: true, defaultHasFlag: false },
  { id: 8, key: "autoimmuneLiverDisease", name: "自身免疫性肝病", showFlag: true, defaultHasFlag: false },
  { id: 9, key: "chronicKidneyDisease", name: "慢性肾脏病", showFlag: true, defaultHasFlag: false },
  { id: 10, key: "nephroticSyndrome", name: "肾病综合征", showFlag: true, defaultHasFlag: false },
  { id: 11, key: "diabetesMellitus", name: "糖尿病", showFlag: true, defaultHasFlag: false },
  { id: 12, key: "hyperthyroidism", name: "甲状腺功能亢进症", showFlag: true, defaultHasFlag: false },
  { id: 13, key: "hypothyroidism", name: "甲状腺功能减退症", showFlag: true, defaultHasFlag: false },
  { id: 14, key: "stroke", name: "脑卒中", showFlag: true, defaultHasFlag: false },
  { id: 15, key: "epilepsy", name: "癫痫", showFlag: true, defaultHasFlag: false },
  { id: 16, key: "parkinsonDisease", name: "帕金森综合症", showFlag: true, defaultHasFlag: false },
  { id: 17, key: "alzheimersDisease", name: "阿尔茨海默病（老年痴呆）", showFlag: true, defaultHasFlag: false },
  { id: 18, key: "myastheniaGravis", name: "重症肌无力", showFlag: true, defaultHasFlag: false },
  { id: 19, key: "als", name: "肌萎缩侧索硬化症", showFlag: true, defaultHasFlag: false },
  { id: 20, key: "glaucoma", name: "青光眼", showFlag: true, defaultHasFlag: false },
  { id: 21, key: "macularDegeneration", name: "黄斑性眼病", showFlag: true, defaultHasFlag: false },
  { id: 22, key: "psoriasisNonBiologic", name: "银屑病（非生物制剂治疗）", showFlag: true, defaultHasFlag: false },
  { id: 23, key: "psoriasisBiologic", name: "银屑病（生物制剂治疗）", showFlag: true, defaultHasFlag: false },
  { id: 24, key: "vitiligo", name: "白癜风", showFlag: true, defaultHasFlag: false },
  { id: 25, key: "chronicHepatitisB", name: "慢性乙型肝炎", showFlag: true, defaultHasFlag: false },
  { id: 26, key: "chronicHepatitisCNon1B", name: "慢性丙型肝炎（非1B型）", showFlag: true, defaultHasFlag: false },
  { id: 27, key: "chronicHepatitisC1B", name: "慢性丙型肝炎（1B型）", showFlag: true, defaultHasFlag: false },
  { id: 28, key: "nonDrugResistantTuberculosis", name: "非耐药性结核病", showFlag: true, defaultHasFlag: false },
  { id: 29, key: "aids", name: "艾滋病", showFlag: true, defaultHasFlag: false },
  { id: 30, key: "rheumatoidArthritis", name: "类风湿性关节炎", showFlag: true, defaultHasFlag: false },
  { id: 31, key: "ankylosingSpondylitis", name: "强直性脊柱炎", showFlag: true, defaultHasFlag: false },
  { id: 32, key: "behcetDisease", name: "白塞氏病", showFlag: true, defaultHasFlag: false },
  { id: 33, key: "systemicSclerosis", name: "系统性硬化症", showFlag: true, defaultHasFlag: false },
  { id: 34, key: "sjogrenSyndrome", name: "干燥综合征", showFlag: true, defaultHasFlag: false },
  { id: 35, key: "polymyositis", name: "多发性肌炎", showFlag: true, defaultHasFlag: false },
  { id: 36, key: "dermatomyositis", name: "皮肌炎", showFlag: true, defaultHasFlag: false },
  { id: 37, key: "polyarteritisNodosa", name: "结节性多动脉炎", showFlag: true, defaultHasFlag: false },
  { id: 38, key: "cerebralPalsy", name: "脑瘫", showFlag: true, defaultHasFlag: false },
  { id: 39, key: "liverCirrhosis", name: "肝硬化", showFlag: true, defaultHasFlag: false },
  { id: 40, key: "mentalDisorderNonSecondGenLongActingInjection", name: "精神障碍（非第二代长效针剂治疗）", showFlag: true, defaultHasFlag: false },
  { id: 41, key: "mentalDisorderSecondGenLongActingInjection", name: "精神障碍（第二代长效针剂治疗）", showFlag: true, defaultHasFlag: false },
  { id: 42, key: "ancaAssociatedVasculitis", name: "ANCA相关血管炎", showFlag: true, defaultHasFlag: false },
  { id: 43, key: "postValveReplacement", name: "心脏瓣膜置换术后", showFlag: true, defaultHasFlag: false },
  { id: 44, key: "postStentPlacement", name: "血管支架植入术后", showFlag: true, defaultHasFlag: false },
  { id: 45, key: "postCABG", name: "心脏冠脉搭桥术后", showFlag: true, defaultHasFlag: false },
  { id: 46, key: "progressiveMuscularDystrophy", name: "进行性肌营养不良症", showFlag: true, defaultHasFlag: false },
  { id: 47, key: "severeVernalKeratoconjunctivitis", name: "严重性春季角结膜炎", showFlag: true, defaultHasFlag: false },
  { id: 48, key: "chronicUrticariaCommon", name: "慢性荨麻疹（普通型）", showFlag: true, defaultHasFlag: false },
  { id: 49, key: "chronicUrticariaRefractory", name: "慢性荨麻疹（难治型）", showFlag: true, defaultHasFlag: false },
  { id: 50, key: "paroxysmalNocturnalHemoglobinuria", name: "阵发性睡眠性血红蛋白尿", showFlag: true, defaultHasFlag: false },
  { id: 51, key: "atypicalHemolyticUremicSyndrome", name: "非典型溶血性尿毒症", showFlag: true, defaultHasFlag: false },
  { id: 52, key: "narcolepsy", name: "发作性睡病", showFlag: true, defaultHasFlag: false },
  { id: 53, key: "hypophosphatemicRickets", name: "低磷性佝偻病", showFlag: true, defaultHasFlag: false },
  { id: 54, key: "shortBowelSyndrome", name: "短肠综合征", showFlag: true, defaultHasFlag: false }
]

